In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprice.csv')

In [3]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
df['bedrooms'].median()

3.5

In [6]:
import math

In [7]:
median_bedrooms = math.floor(df['bedrooms'].median())

In [8]:
median_bedrooms

3

In [9]:
df['bedrooms'].fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [11]:
df['bedrooms'] = df['bedrooms'].fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [12]:
linreg = linear_model.LinearRegression()

In [16]:
linreg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [17]:
linreg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [18]:
linreg.intercept_

383724.9999999998

In [19]:
linreg.predict([[3000,3,40]])

array([444400.])

In [20]:
linreg.predict([[2500,4,5]])

array([588625.])